apiVersion: apps/v1
kind: Deployment
metadata:
  name: kishoretest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kishoretest
  template:
    metadata:
      labels:
        app: kishoretest
    spec:
      containers:
        - name: testdemo
          image: kishoreking90/gradletest:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: kishoretest
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31114
    port: 4444
    targetPort: 8080
  selector:
    app: kishoretest
