apiVersion: apps/v1
kind: Deployment
metadata:
  name: kishoretest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kishoretest
  template:
    metadata:
      labels:
        app: kishoretest
    spec:
      containers:
        - name: testdemo
          image: kishoreking90/gradletest:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: kishoretest
spec:
  type: LoadBalancer
  selector:
    app: kishoretest
  ports:
    - name: http
      port: 8080
      nodePort: 31114
